export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED'
}

export enum EMAIL_VERIFY {
  VERIFY = 'VERIFY',
  UNVERIFY = 'UNVERIFY'
}

export enum PHONE_VERIFY {
  VERIFY = 'VERIFY',
  UNVERIFY = 'UNVERIFY'
}
